### ISSUE TITLE
[3pts] Create Food List Page

### ISSUE THREAD

**Issue by IndieCoderMM** [tobuya/kitchen-genie#3]
## Requirements
- Food list (only for a group that has less than 3 members):
  - Should display a list of food added by the logged-in user as in the wireframe (display also quantity of a given food).
  - Should lead to a form that allows users to add new food.

## Tasks
- [ ] Create routes for `Food`
- [ ] Add actions in `FoodsController`
- [ ] Create a view for the `food#index` page

## Wireframe
![food_index](https://user-images.githubusercontent.com/72640048/233947737-eaa99c30-87b8-432f-a427-41e768952b80.png)
