### ISSUE TITLE
[4pts] Create Public Recipes Page

### ISSUE THREAD

**Issue by IndieCoderMM** [tobuya/kitchen-genie#7]
## Requirements
- Public recipe list:
  - Should display a list of all public recipes ordered by the newest as in the wireframe.
  - Should lead to recipe details.

## Tasks
- [ ] Define the `#index` action in `PublicRecipesController`
- [ ] Select all recipes with `public: true` from the database
- [ ] Create a view to display the public recipes

## Wireframe
![public_recipe_index](https://user-images.githubusercontent.com/72640048/233951002-406f52b1-75a7-46aa-aaee-c311ca8f35c5.png)
