### ISSUE TITLE
[4pts] Create Recipe Detail Page

### ISSUE THREAD

**Issue by IndieCoderMM** [tobuya/kitchen-genie#8]
## Requirements
- Recipe details:
  - Should display a toggle button that allows for a recipe to be made public or private.
  - If the recipe is public or the user is the owner of the recipe, should display the recipe details as in the wireframe.
  - If the user is the owner of the recipe, should lead to the form that allows the user to add new food.

## Tasks
- [ ] Create a view to display a recipe 
- [ ] Create a toggle button
- [ ] Create form to add new food

## Wireframe
![recipe_food](https://user-images.githubusercontent.com/72640048/233952430-9cfe281b-026a-48f0-89ce-d21ede5c02a3.png)
