### ISSUE TITLE
[4pts] Create General Shopping List Page (Group)

### ISSUE THREAD

**Issue by IndieCoderMM** [tobuya/kitchen-genie#9]
## Requirements
- General shopping list view (only for a group that has less than 3 members):
  - Should show the list of food that is missing for all recipes of the logged-in user (compare the list of food for all recipes with the general food list of that user).
  - Should count the total food items and total price of the missing food.

## Tasks
- [ ] Create a view for the shopping list
- [ ] Display the list of missing food 
- [ ] Calculate the total items and price of missing food

## Wireframe
![general_shopping_list](https://user-images.githubusercontent.com/72640048/233953607-bc77a49e-d57f-4837-95e3-88cf40650082.png)
